export enum WagerTransactionKind {
  Opening = "OPENING",
  Bet = "BET",
  Win = "WIN",
  Loss = "LOSS",
  Refund = "REFUND",
  Rollback = "ROLLBACK",
}

export enum WagerTransactionStatus {
  Pending = "PENDING",
  PendingReference = "PENDING_REFERENCE",
  Processed = "PROCESSED",
  Rejected = "REJECTED",
  Failed = "FAILED",
}

export const FailureCode = {
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  REVERSAL_WOULD_OVERDRAW: "REVERSAL_WOULD_OVERDRAW",
  IDEMPOTENCY_PAYLOAD_CONFLICT: "IDEMPOTENCY_PAYLOAD_CONFLICT",
  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  DUPLICATE_WALLET: "DUPLICATE_WALLET",
  INVALID_KIND: "INVALID_KIND",
  OPENING_NOT_ALLOWED: "OPENING_NOT_ALLOWED",
  REFERENCE_REQUIRED: "REFERENCE_REQUIRED",
  REFERENCE_NOT_FOUND: "REFERENCE_NOT_FOUND",
  REFERENCE_ALREADY_REVERSED: "REFERENCE_ALREADY_REVERSED",
  REFERENCE_AMOUNT_MISMATCH: "REFERENCE_AMOUNT_MISMATCH",
  REFERENCE_SCOPE_MISMATCH: "REFERENCE_SCOPE_MISMATCH",
  REFERENCE_KIND_NOT_ALLOWED: "REFERENCE_KIND_NOT_ALLOWED",
  REFERENCE_NOT_PROCESSED: "REFERENCE_NOT_PROCESSED",
  INVALID_MONEY: "INVALID_MONEY",
  TRANSACTION_NOT_FOUND: "TRANSACTION_NOT_FOUND",
  INFRA_PERMANENT: "INFRA_PERMANENT",
} as const;

export type FailureCode = (typeof FailureCode)[keyof typeof FailureCode];
